version: 2.1

parameters:
  run_workflow:
    type: boolean
    default: false

jobs:
  build:
   command: npm run build
  
workflows:
  version: 2
 
  build_master:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only: master
    jobs: &build_master
      - build

  build_master_manual:
    when: << pipeline.parameters.run_workflow >>
    jobs: *build_master