version: 2.1

jobs:
  build:
   command: npm run build
  
workflows:
  version: 2
 
  build_master:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only: master
    jobs: &build_master
      - build


