name: Scheduled build
on:
  schedule:
  - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our build webhook on Netlify
    - run: |
        npm ci
        npm run build
      env:
        TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
