name: Scheduled build
on:
  schedule:
  - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our NPM install
      run: npm install
    - name: Trigger our NPM build
      run: npm run build --if-present
      env:
        CI: true
